export const ENV = {
  appId: process.env.AUTH_MODE === "local" ? "local" : (process.env.VITE_APP_ID ?? ""),
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  authMode: process.env.AUTH_MODE === "local" ? "local" : "manus",
  localAdminOpenId: process.env.LOCAL_ADMIN_OPEN_ID ?? "local-owner",
  localAdminName: process.env.LOCAL_ADMIN_NAME ?? "개인 사용자",
  localAdminPassword: process.env.LOCAL_ADMIN_PASSWORD ?? "",
  storageMode: process.env.STORAGE_MODE === "local" ? "local" : "forge",
  localStorageDir: process.env.LOCAL_STORAGE_DIR ?? "./data/uploads",
};
